
import Navbar from "@components/Navbar";

import "@styles/global.css";

export const metadata = {
  title: "my-app",
  description: "Generated by tesfa",
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <main className="">{children}</main>
        
      </body>
    </html>
  );
};

export default Layout;
